GET http://localhost:4000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTYxNTkyMDQ4N30.mm2eZ8U27saQp7HlzarnEgbP5BSzV0mwpk6COcdAxdo
###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "Kyle"
}