GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTYxNTkyMTU5NCwiZXhwIjoxNjE1OTIxNjA5fQ.edW32LY4Vv2Gk8OwiEtlqDV49u6mKlAL4KjUb7ctcsE
###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTYxNTkyMTcyOX0.qLR35zr0NUPcvVoJrHQMEJqlADTK6EWPLkKDYF8hFp8"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "Kyle"
}